/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "odtwqmdjahoyknbghtjs";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kdHdxbWRqYWhveWtuYmdodGpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAwNTQ4MzgsImV4cCI6MjA5NTYzMDgzOH0.dsm8S7Cb6x4iYyL-LfPNvN7oSiS-Jy0wsVI5fG8OSjQ";
